---
- name: nginx install and start services
  hosts: jenkinsservers
  remote_user: vagrant
  become: yes
  tasks:
    - name: update repo list
      yum: name={{ item }} state=latest
      with_items:
        - epel-release
        - java-openjdk
        - wget
    
    - name: install nginx
      yum: name={{ item }} state=latest
      with_items:
        - nginx

    - name: add jenkins to repo
      shell: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    
    - name: import repo key
      become: yes
      shell: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
    
    - name: install jenkins
      yum: name={{ item }} state=latest
      with_items:
        - jenkins
    
    - name: Habilitando jenkins e nginx service starts on boot
      service: name={{ item }} state=started enabled=yes
      with_items:
        - jenkins
        - nginx

    - name: check rules fw works
      shell: ss -tunelp | grep 8080